### ISSUE TITLE
how to compile on Visual Studio 2017?

### ISSUE THREAD

**Issue by RPG3D** [janbar/openssl-cmake#1]
I got some errors. 

Error	C4235	nonstandard extension used: '__int128' keyword not supported on this architecture	crypto	e:\ue4proj\openssl-cmake-up_to_1.1.1\crypto\poly1305\poly1305_base2_44.c	21

**Comment by janbar** [comment]
This branch isn't ready to use. You should try the **master** branch (1.1.0). It works on OSX, Linux and Android arm/x86. But never try on Windows ;-) . Let me know if it works.

**Comment by RPG3D** [comment]
Hi, I am stop use the openssl source. I am compile curl on UE4, the compile env in UE4 is so strict, the openssl code more loose than UE4, still got some errors . now, I think I can use the prebuild openssl library in UE4.
