### ISSUE TITLE
check_type_size does not work

### ISSUE THREAD

**Issue by EndrII** [janbar/openssl-cmake#13]
i have a problem 

***CMakeLists.txt:144 (check_type_size)***
in this [line](https://github.com/janbar/openssl-cmake/blob/ac7f4fdb0766fa6aef4fb260788820e282919b33/CMakeLists.txt#L144) : 
cmake version: 3.11 and 3.17

OS
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

Cmake log :
``` cmake
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
 not exits in /root/worker/cmake/LinuxCMakeBuilder/build/SimpleQmlNotify/CMake/crossplatform/Linux/.cmake
 LIB_OUTPUT_DIR = /root/worker/cmake/LinuxCMakeBuilder/build/SimpleQmlNotify/build/Release
-- buid type    Release
-- Project      QmlNotyfyService
-- c compiler   /usr/bin/cc
-- cxx compiler /usr/bin/c++
-- build shared 
-- qmake exec   
using ccache in /usr/bin/ccache
using ccache in /usr/bin/ccache
 not exits in /root/worker/cmake/LinuxCMakeBuilder/build/QtNetworkProtocol/QuasarAppLib/CMake/crossplatform/Linux/.cmake
 LIB_OUTPUT_DIR = /root/worker/cmake/LinuxCMakeBuilder/build/QtNetworkProtocol/QuasarAppLib/build/Release
-- buid type    Release
-- Project      QuasarApp
-- c compiler   /usr/bin/cc
-- cxx compiler /usr/bin/c++
-- build shared 
-- qmake exec   
-- OpenSSL version 1.1.1e
CMake Error at /usr/share/cmake-3.10/Modules/CheckIncludeFile.cmake:46 (configure_file):
  configure_file attempted to configure a file:
  /root/worker/cmake/LinuxCMakeBuilder/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
  into a source directory.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CheckTypeSize.cmake:223 (check_include_file)
  QtNetworkProtocol/openssl-cmake/CMakeLists.txt:144 (check_type_size)
-- Configuring incomplete, errors occurred!
See also "/root/worker/cmake/LinuxCMakeBuilder/build/CMakeFiles/CMakeOutput.log".
program finished with exit code 1
elapsedTime=2.454305
```
[CMakeOutput.log](https://github.com/janbar/openssl-cmake/files/4481143/CMakeOutput.log)

Any help please.

**Comment by cowboylym** [comment]
> i have a problem
> 
> _**CMakeLists.txt:144 (check_type_size)**_
> in this [line](https://github.com/janbar/openssl-cmake/blob/ac7f4fdb0766fa6aef4fb260788820e282919b33/CMakeLists.txt#L144) :
> cmake version: 3.11 and 3.17
> 
> OS
> Distributor ID: Ubuntu
> Description: Ubuntu 18.04.4 LTS
> Release: 18.04
> Codename: bionic
> 
> Cmake log :
> 
> ```cmake
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is GNU 7.5.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
>  not exits in /root/worker/cmake/LinuxCMakeBuilder/build/SimpleQmlNotify/CMake/crossplatform/Linux/.cmake
>  LIB_OUTPUT_DIR = /root/worker/cmake/LinuxCMakeBuilder/build/SimpleQmlNotify/build/Release
> -- buid type    Release
> -- Project      QmlNotyfyService
> -- c compiler   /usr/bin/cc
> -- cxx compiler /usr/bin/c++
> -- build shared 
> -- qmake exec   
> using ccache in /usr/bin/ccache
> using ccache in /usr/bin/ccache
>  not exits in /root/worker/cmake/LinuxCMakeBuilder/build/QtNetworkProtocol/QuasarAppLib/CMake/crossplatform/Linux/.cmake
>  LIB_OUTPUT_DIR = /root/worker/cmake/LinuxCMakeBuilder/build/QtNetworkProtocol/QuasarAppLib/build/Release
> -- buid type    Release
> -- Project      QuasarApp
> -- c compiler   /usr/bin/cc
> -- cxx compiler /usr/bin/c++
> -- build shared 
> -- qmake exec   
> -- OpenSSL version 1.1.1e
> CMake Error at /usr/share/cmake-3.10/Modules/CheckIncludeFile.cmake:46 (configure_file):
>   configure_file attempted to configure a file:
>   /root/worker/cmake/LinuxCMakeBuilder/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
>   into a source directory.
> Call Stack (most recent call first):
>   /usr/share/cmake-3.10/Modules/CheckTypeSize.cmake:223 (check_include_file)
>   QtNetworkProtocol/openssl-cmake/CMakeLists.txt:144 (check_type_size)
> -- Configuring incomplete, errors occurred!
> See also "/root/worker/cmake/LinuxCMakeBuilder/build/CMakeFiles/CMakeOutput.log".
> program finished with exit code 1
> elapsedTime=2.454305
> ```
> 
> [CMakeOutput.log](https://github.com/janbar/openssl-cmake/files/4481143/CMakeOutput.log)
> 
> Any help please.

you should build in sorce_root/build folder

**Comment by EndrII** [comment]
why should this help?

**Comment by Nemirtingas** [comment]
Hi,
Personally, I just define em on the CMake command line:
```
mkdir build && cd build
cmake -DLONG_INT=4 -DLONG_LONG_INT=8 -Wno-dev -DCMAKE_BUILD_TYPE=Release ..
```

**Comment by EndrII** [comment]
thanks )

**Comment by Nemirtingas** [comment]
Np, I encoutered this error while cross-compiling openssl on Linux for Windows ;).
